# Generated by Django 5.2.1 on 2025-07-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product",
            new_name="product_obj",
        ),
    ]
