# Generated by Django 5.2.1 on 2025-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_rename_product_cartitem_product_obj"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
