# Generated by Django 5.2.1 on 2025-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default/default-user.png", upload_to="userprofile"
            ),
        ),
    ]
