# Generated by Django 5.2.1 on 2025-08-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line_1",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
